#!/usr/bin/env python3
# Auto-generated by MissingLink encrypter.py. Safe to publish.
from __future__ import annotations

import base64
import hashlib
import json
import os
import struct
import subprocess
import sys
import urllib.error
import urllib.request
import zlib
from pathlib import Path

MAGIC = b"MLPKG1\x00"
DEFAULT_PACKAGE = "h3_studio_3.mlpkg"
KEY_ENDPOINT = os.environ.get("MISSINGLINK_PACKAGE_KEY_URL", "https://missinglink.build/api/notebook/package-key").strip()


def _b64u_decode(value: str) -> bytes:
    value = value.strip()
    return base64.urlsafe_b64decode(value + "=" * ((4 - len(value) % 4) % 4))


def _read_token() -> str:
    token = (os.environ.get("MISSING_LINK_TOKEN") or "").strip()
    if not token:
        try:
            from google.colab import userdata
            token = (userdata.get("MISSING_LINK_TOKEN") or "").strip()
        except Exception:
            token = ""
    if not token:
        raise SystemExit(
            "MISSING_LINK_TOKEN is not set. Add it to Colab Secrets, enable notebook access, and rerun."
        )
    os.environ["MISSING_LINK_TOKEN"] = token
    return token


def _ensure_crypto():
    try:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
        return AESGCM
    except Exception:
        subprocess.run([sys.executable, "-m", "pip", "install", "-q", "cryptography>=42"], check=True)
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
        return AESGCM


def _read_package(path: Path):
    raw = path.read_bytes()
    if len(raw) < len(MAGIC) + 4 or not raw.startswith(MAGIC):
        raise SystemExit(f"Invalid MissingLink package: {path}")
    off = len(MAGIC)
    header_len = struct.unpack(">I", raw[off:off+4])[0]
    off += 4
    if header_len <= 0 or header_len > 1024 * 1024 or off + header_len > len(raw):
        raise SystemExit("Corrupt MissingLink package header")
    header_bytes = raw[off:off+header_len]
    off += header_len
    try:
        header = json.loads(header_bytes.decode("utf-8"))
    except Exception as exc:
        raise SystemExit(f"Corrupt MissingLink package metadata: {exc}")
    ciphertext = raw[off:]
    if not ciphertext:
        raise SystemExit("Missing encrypted payload")
    return header, ciphertext


def _request_key(token: str, header: dict) -> bytes:
    body = json.dumps({
        "build_id": header["build_id"],
        "salt_b64": header["salt_b64"],
        "source_sha256": header["source_sha256"],
        "package_version": header.get("version", 1),
    }, separators=(",", ":")).encode("utf-8")
    req = urllib.request.Request(
        KEY_ENDPOINT,
        data=body,
        headers={
            "x-api-key": token,
            "content-type": "application/json",
            "accept": "application/json",
            "user-agent": "MissingLink-Protected-Notebook/1",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            data = json.loads(resp.read(65536).decode("utf-8", "replace"))
    except urllib.error.HTTPError as exc:
        # Never print auth bodies; they may contain account details.
        raise SystemExit(f"MissingLink license rejected this runtime (HTTP {exc.code}).") from None
    except Exception as exc:
        raise SystemExit(f"Could not contact MissingLink license service: {type(exc).__name__}: {exc}") from None
    if not data.get("ok") or not data.get("key_b64"):
        raise SystemExit("MissingLink did not authorize this protected notebook build.")
    key = _b64u_decode(str(data["key_b64"]))
    if len(key) != 32:
        raise SystemExit("MissingLink returned an invalid build key")
    return key


def main() -> None:
    AESGCM = _ensure_crypto()
    token = _read_token()
    package_env = (os.environ.get("MISSINGLINK_PACKAGE_PATH") or "").strip()
    package = Path(package_env) if package_env else Path(__file__).resolve().with_name(DEFAULT_PACKAGE)
    package = package.resolve()
    header, ciphertext = _read_package(package)

    key = _request_key(token, header)
    nonce = _b64u_decode(header["nonce_b64"])
    aad = _b64u_decode(header["aad_b64"])
    try:
        compressed = AESGCM(key).decrypt(nonce, ciphertext, aad)
        source_bytes = zlib.decompress(compressed)
    except Exception:
        raise SystemExit("Protected notebook package failed authentication/decryption.") from None

    got = hashlib.sha256(source_bytes).hexdigest()
    if got != header["source_sha256"]:
        raise SystemExit("Protected notebook source hash mismatch")

    # Required by H3's Blackwell isolated-child path.  When the decrypted source
    # wants to relaunch itself, it launches THIS loader instead, which performs a
    # fresh online subscription check and decrypts the package again in memory.
    os.environ["MISSINGLINK_PROTECTED_LAUNCHER"] = str(Path(__file__).resolve())
    os.environ["MISSINGLINK_PACKAGE_PATH"] = str(package)

    filename = header.get("original_filename") or "protected_notebook.py"
    source = source_bytes.decode("utf-8")
    code = compile(source, f"<missinglink:{filename}>", "exec", dont_inherit=True)

    # Best-effort removal of the large plaintext byte buffer before user code runs.
    source_bytes = b""
    compressed = b""
    key = b""

    globs = {
        "__name__": "__main__",
        "__file__": filename,
        "__package__": None,
        "__cached__": None,
        "__builtins__": __builtins__,
    }
    exec(code, globs, globs)


if __name__ == "__main__":
    main()
